<style>
    a:link,
    a:visited
    {
        color: #FFFFFF;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>
	
	Menu: 
	<?php 
	  foreach ($this->menu as $key => $value): 
	?>
	<a href="<?php echo $this->url(array('action' => $key), 'default', true); ?>"><?php echo $value; ?></a> |
	<?php
	  endforeach;
	?>

	<br /><br />
   ... our application is based on ZF 1.12

</div>